In [1]:
from torchsummary import summary
from torch import nn
import torch

In [2]:
import sys
sys.path.append("/home/wuwenjun/jupyter_code/Shannon/AlphaNet")

In [3]:
from AlphaNet import Model_Loader

In [4]:
from AlphaNet.Models import AlphaNet_LSTM_V1
from AlphaNet import Model_Loader
from torch import optim
LR = 0.01
epoch_num = 10
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
loss_function = nn.MSELoss()


model = AlphaNet_LSTM_V1(108, 30)
optimizer = optim.Adam(model.parameters(), lr=LR)
model_loader = Model_Loader(model = model,optimizer=optimizer,device=device)
print(model_loader.model)

AlphaNet_LSTM_V1(
  (batch): BatchNorm1d(108, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (lstm): LSTM(108, 30, num_layers=2, batch_first=True, bidirectional=True)
  (batch2): BatchNorm1d(30, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (out): Linear(in_features=30, out_features=1, bias=True)
)


In [5]:
model_loader.fit()

TypeError: fit() missing 3 required positional arguments: 'dataloader', 'loss_function', and 'epoch_num'

In [53]:
from AlphaNet import Model_Loader

In [54]:
a = Model_Loader()

TypeError: __init__() missing 2 required positional arguments: 'model' and 'optimizer'

In [3]:
import torch 
from torch import nn

In [13]:
BN = nn.BatchNorm1d(2)
input = torch.randn(1,2,3)
print(input)
output = BN(input)
output

tensor([[[ 0.5686,  0.6567, -0.7383],
         [ 0.2997,  0.4921,  0.6371]]])


tensor([[[ 0.6369,  0.7751, -1.4119],
         [-1.2775,  0.1141,  1.1634]]], grad_fn=<NativeBatchNormBackward0>)

In [6]:
output

tensor([[ 1.3630e+00,  7.4460e-01, -1.9111e+00,  ..., -4.3289e-01,
          6.6744e-01,  3.0721e-01],
        [ 1.3268e-01, -5.5407e-01,  4.0296e-01,  ...,  1.0542e+00,
         -2.1182e-03, -7.9322e-01],
        [-6.8179e-01,  9.5086e-01, -2.6324e-01,  ..., -1.1121e+00,
          8.8490e-01,  1.3108e+00],
        ...,
        [ 4.1631e-01,  7.0531e-01, -1.1987e+00,  ..., -1.0320e+00,
         -5.0324e-01,  4.9155e-01],
        [ 2.0755e+00, -1.8278e+00,  1.1462e+00,  ..., -5.2868e-01,
         -4.4903e-01, -6.2559e-01],
        [-3.4253e-01,  2.4919e+00,  1.6544e+00,  ...,  6.6577e-01,
          6.5799e-01,  1.0095e+00]], grad_fn=<NativeBatchNormBackward0>)

In [27]:
model_loader.fit()

AttributeError: 'Model_Loader' object has no attribute 'fit'

In [18]:
alphanet = AlphaNet_LSTM(108, 30)
alphanet = alphanet.cuda()
summary(alphanet, input_size=(108, 3))

AttributeError: 'tuple' object has no attribute 'size'

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchsummary import summary


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = Net().to(device)

summary(model, (1, 28, 28))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 10, 24, 24]             260
            Conv2d-2             [-1, 20, 8, 8]           5,020
         Dropout2d-3             [-1, 20, 8, 8]               0
            Linear-4                   [-1, 50]          16,050
            Linear-5                   [-1, 10]             510
Total params: 21,840
Trainable params: 21,840
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.06
Params size (MB): 0.08
Estimated Total Size (MB): 0.15
----------------------------------------------------------------
