In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

In [9]:
a = np.random.uniform(10,100,(3,3))
b = np.random.uniform(0,1,(1,2,3))

In [5]:
c = np.array([a,b])
c = c.reshape(3,2)

NameError: name 'a' is not defined

In [2]:
c= np.array(
        [[[70.49739271, 11.31741861],
        [0.68245192, 0.76345192]],

       [[61.76578482, 59.31703701],
        [ 0.354265192,  0.82355827]],

       [[ 32.95965432,  35.81408566],
        [ 0.54267866,  0.96221199]]]
           )

In [11]:
a

array([[50.37681382, 21.73519784, 75.97103974],
       [60.33703627, 53.39697793, 36.90881324],
       [92.07502065, 91.85119001, 23.33707187]])

In [13]:
day = 1

In [20]:
a[0:2,:-1]

array([[50.37681382, 21.73519784],
       [60.33703627, 53.39697793]])

In [19]:
a[1,-1]

36.90881324410529

In [28]:
batch(c)

tensor([[[ 1.2356, -1.6639],
         [-0.0287,  0.3833]],

        [[ 0.8078,  0.6878],
         [-1.6983,  0.6891]],

        [[-0.6036, -0.4637],
         [-0.7398,  1.3944]]], grad_fn=<NativeBatchNormBackward>)