In [1]:
import pandas as pd
import numpy as np

In [24]:
import numpy as np

data = np.random.randn(3,1,2,10) # 数据产生
mean = data.mean(axis = 3, keepdims=True)
mean.shape
x1 = data[:,:,[0,1],:]-mean
y1 = data[:,:,[1,0],:]-mean  # 矩阵翻转
coef = (x1*y1).sum(axis = 3, keepdims=True)/(10-1)
print(coef)

[[[[ 0.3278148 ]
   [ 0.3278148 ]]]


 [[[ 0.03680641]
   [ 0.03680641]]]


 [[[-0.20326324]
   [-0.20326324]]]]


In [25]:
coef.shape

(3, 1, 2, 1)

In [37]:
test_data = data[0].reshape(2,10)
print(np.cov(test_data))
test_data = data[1].reshape(2,10)
print(np.cov(test_data))
test_data = data[2].reshape(2,10)
print(np.cov(test_data))

[[0.61772345 0.3278148 ]
 [0.3278148  1.56895142]]
[[0.93494175 0.03680641]
 [0.03680641 0.80959483]]
[[ 0.75506948 -0.20326324]
 [-0.20326324  1.12753887]]
