In [1]:
import pandas as pd
import numpy as np

In [2]:
import numpy as np

data = np.random.randn(3,1,2,10) # 数据产生
mean = data.mean(axis = 3, keepdims=True)
mean.shape
x1 = data[:,:,[0,1],:]-mean
y1 = data[:,:,[1,0],:]-mean  # 矩阵翻转
coef = (x1*y1).sum(axis = 3, keepdims=True)/(10-1)
print(coef)

[[[[-0.27873982]
   [-0.27873982]]]


 [[[-0.24735937]
   [-0.24735937]]]


 [[[ 0.71058634]
   [ 0.71058634]]]]


In [25]:
coef.shape

(3, 1, 2, 1)

In [3]:
test_data = data[0].reshape(2,10)
print(np.cov(test_data))
test_data = data[1].reshape(2,10)
print(np.cov(test_data))
test_data = data[2].reshape(2,10)
print(np.cov(test_data))

[[ 1.78068107 -0.27873982]
 [-0.27873982  0.56578419]]
[[ 1.02571662 -0.24735937]
 [-0.24735937  0.98954489]]
[[1.00555427 0.71058634]
 [0.71058634 0.86136528]]


In [12]:
data=np.random.uniform(10,100,(2000,1,9,30))
def generateC(l1):
    if len(l1) == 1:
        return []
    v = [[l1[0],i] for i in l1[1:]]
    l1 = l1[1:]
    return v+generateC(l1)
feat_nums = data.shape[2]
feat_nums
list1 = list(range(feat_nums))
num = generateC(list1)
num_rev = []
for l in num:
    l1 = l.copy()
    l1.reverse()
    num_rev.append(l1)
print(num,'\n',num_rev)
# feat_nums = data.shape[2]
# list1 = list(range(feat_nums))  # 4为特征数
# num = generateC(list1)
# num_rev = [] # 数组反转,PS:不要用[l.reverse() for l in num],因为reverse函数会直接修改原List，不会产生新的结果。
# for l in num:
#     l1 = l.copy()
#     l1.reverse()
#     num_rev.append(l1)
#  print(num,'\n',num_rev)

[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7], [1, 8], [2, 3], [2, 4], [2, 5], [2, 6], [2, 7], [2, 8], [3, 4], [3, 5], [3, 6], [3, 7], [3, 8], [4, 5], [4, 6], [4, 7], [4, 8], [5, 6], [5, 7], [5, 8], [6, 7], [6, 8], [7, 8]] 
 [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [6, 0], [7, 0], [8, 0], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1], [8, 1], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [4, 3], [5, 3], [6, 3], [7, 3], [8, 3], [5, 4], [6, 4], [7, 4], [8, 4], [6, 5], [7, 5], [8, 5], [7, 6], [8, 6], [8, 7]]


NameError: name 'stride' is not defined

In [25]:
stride = 10
data_length = data.shape[3] # 30
feat_num = data.shape[2] # 9
conv_feat = len(num) # 组合特征的数量 36
if data_length % stride == 0:
    step_list = list(range(0,data_length+stride,stride))
elif data_length % stride<=5:
    mod = data_length % stride
    step_list = list(range(0,data_length-stride,stride))+[data_length]
else:
    mod = data_length % stride
    step_list = list(range(0,data_length+stride-mod,stride))+[data_length]
l = []
#计算的过程中务必保持keepdims=True
for i in range(len(step_list)-1):
    start = step_list[i]
    end = step_list[i+1]
    sub_data1 = data[:,:,num,start:end]
    sub_data2 = data[:,:,num_rev,start:end]
#     mean1 = sub_data1.mean(axis = 4,keepdims = True)
#     mean2 = sub_data2.mean(axis = 4,keepdims = True)
#     spread1 = sub_data1 - mean1
#     spread2 = sub_data2 - mean2
#     cov = ((spread1*spread2).sum(axis = 4,keepdims = True)/(sub_data1.shape[4] - 1)).mean(axis = 3,keepdims = True)
#     l.append(cov)
# conv_feat = len(num)
# corr = np.squeeze(np.array(l)).transpose(1,2,0).reshape(-1,1,conv_feat,len(step_list)-1)

(2000, 1, 36, 2, 10)

In [27]:
import pytorch

ModuleNotFoundError: No module named 'pytorch'